"""
Fallback Service

Generates unique, clearly synthetic placeholder values for missing required fields.
Placeholders MUST:
 - Be obviously artificial (prefixed with AUTO-MISSING-*)
 - Never collide with legitimate business data
 - Be unique (uses secrets.token_hex for randomness)
 - Never be mistaken for real data (business logic must check is_placeholder())
"""
import secrets
import re


# Prefix pattern that identifies all generated placeholders
PLACEHOLDER_PREFIX = "AUTO-MISSING-"
PLACEHOLDER_PATTERN = re.compile(r"^AUTO-MISSING-[A-Z]+-[0-9A-F]{8}$")


def _generate_token() -> str:
    """Generate 8 uppercase hex characters (4 random bytes)."""
    return secrets.token_hex(4).upper()


def generate_placeholder(field_label: str) -> str:
    """
    Generate a unique synthetic placeholder for a missing required field.

    Args:
        field_label: Short uppercase label describing the field.
                     e.g. "BATCH", "SKU", "EXPIRY", "PHONE"

    Returns:
        e.g. "AUTO-MISSING-BATCH-8F31C2A0"

    Examples:
        >>> generate_placeholder("BATCH")
        'AUTO-MISSING-BATCH-3FA2B1C0'
        >>> generate_placeholder("SKU")
        'AUTO-MISSING-SKU-0E1A2B3C'
    """
    label = field_label.strip().upper().replace(" ", "_")
    return f"{PLACEHOLDER_PREFIX}{label}-{_generate_token()}"


def is_placeholder(value: str | None) -> bool:
    """
    Return True if the value is a synthetic placeholder generated by this service.
    This is the AUTHORITATIVE check — never rely on string prefix alone in callers.
    """
    if not value:
        return False
    return bool(PLACEHOLDER_PATTERN.match(value))


# --- Specific generators for each field type ---

def batch_number_placeholder() -> str:
    return generate_placeholder("BATCH")


def sku_placeholder() -> str:
    return generate_placeholder("SKU")


def barcode_placeholder() -> str:
    return generate_placeholder("BARCODE")


def expiry_date_placeholder() -> str:
    """
    Returns a far-future date string for an expiry date placeholder.
    This date is intentionally in the very far future (year 9999) so it
    never participates incorrectly in FEFO logic. Business logic MUST
    exclude rows where is_expiry_placeholder() is True.
    NOTE: The string form is returned; callers must interpret/store appropriately.
    """
    return "9999-12-31"


def is_expiry_placeholder(value: str | None) -> bool:
    """Check if the date string is the synthetic far-future expiry placeholder."""
    if not value:
        return False
    return str(value) == "9999-12-31"


def supplier_placeholder() -> str:
    return generate_placeholder("SUPPLIER")


def phone_placeholder() -> str:
    return generate_placeholder("PHONE")
