"""add_branch_to_sale_and_purchase

Revision ID: 296e8d3ad158
Revises: bac3751faa11
Create Date: 2026-08-26 16:08:37.464506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '296e8d3ad158'
down_revision: Union[str, Sequence[str], None] = 'bac3751faa11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch', sa.String(), nullable=True))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('branch')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('branch')

    # ### end Alembic commands ###
