"""add_store_settings

Revision ID: bac3751faa11
Revises: 28de3f2317df
Create Date: 2026-08-26 15:35:42.865063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac3751faa11'
down_revision: Union[str, Sequence[str], None] = '28de3f2317df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('default_tax_rate', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('store_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_settings_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_settings_id'))

    op.drop_table('store_settings')
    # ### end Alembic commands ###
