"""production_hardening_schema

Revision ID: 31b48f987466
Revises: 3fb8c97a3b4d
Create Date: 2026-08-31 15:47:32.855550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b48f987466'
down_revision: Union[str, Sequence[str], None] = '3fb8c97a3b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('financial_year', sa.String(length=10), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'financial_year', name='uq_invoice_sequence_branch_fy')
    )
    with op.batch_alter_table('invoice_sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_sequences_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_sequences_financial_year'), ['financial_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_sequences_id'), ['id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'UPI', 'CARD', 'BANK_TRANSFER', 'OTHER', name='paymentmethodenum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'PENDING', 'REFUNDED', 'FAILED', name='paymentstatusenum'), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_sale_id'), ['sale_id'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_raw', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone_normalized', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_opt_in', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('whatsapp_opt_in_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.create_index(batch_op.f('ix_customers_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone_normalized'), ['phone_normalized'], unique=False)

    op.execute("UPDATE customers SET phone_raw = phone, phone_normalized = regexp_replace(COALESCE(phone, ''), '[^0-9]', '', 'g') WHERE phone IS NOT NULL")

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_customer_branch_phone', ['branch_id', 'phone_normalized'])

    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_placeholder_expiry', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('is_placeholder_batch', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.alter_column('quantity_available',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               postgresql_using='round(quantity_available)::integer',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('purchase_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='purchase_price::numeric(12, 2)',
               nullable=False,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('mrp',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='mrp::numeric(12, 2)',
               nullable=False,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('selling_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='selling_price::numeric(12, 2)',
               nullable=False,
               existing_server_default=sa.text('0.0'))
        batch_op.create_index('ix_batches_branch_expiry', ['branch_id', 'expiry_date'], unique=False)
        batch_op.create_index('ix_batches_branch_product', ['branch_id', 'product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.alter_column('quantity_change',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               postgresql_using='round(quantity_change)::integer',
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_transactions_branch_timestamp', ['branch_id', 'timestamp'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('units_per_pack', sa.Integer(), server_default=sa.text('1'), nullable=False))
        batch_op.alter_column('mrp',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='mrp::numeric(12, 2)',
               existing_nullable=False)
        batch_op.alter_column('selling_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='selling_price::numeric(12, 2)',
               existing_nullable=False)
        batch_op.alter_column('gst_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               postgresql_using='gst_percentage::numeric(5, 2)',
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))

    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               postgresql_using='round(quantity)::integer',
               existing_nullable=False)
        batch_op.alter_column('purchase_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='purchase_price::numeric(12, 2)',
               existing_nullable=False)
        batch_op.alter_column('mrp',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='mrp::numeric(12, 2)',
               existing_nullable=False)
        batch_op.alter_column('selling_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='selling_price::numeric(12, 2)',
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_purchase_items_purchase_id'), ['purchase_id'], unique=False)

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='total_amount::numeric(12, 2)',
               nullable=False,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('tax_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='tax_amount::numeric(12, 2)',
               nullable=False,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('discount_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='discount_amount::numeric(12, 2)',
               nullable=False,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('grand_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='grand_total::numeric(12, 2)',
               nullable=False,
               existing_server_default=sa.text('0.0'))
        batch_op.create_index('ix_purchases_branch_created', ['branch_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_purchase_date'), ['purchase_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_supplier_id'), ['supplier_id'], unique=False)

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               postgresql_using='round(quantity)::integer',
               existing_nullable=False)
        batch_op.alter_column('unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='unit_price::numeric(12, 2)',
               existing_nullable=False)
        batch_op.alter_column('discount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='discount::numeric(12, 2)',
               nullable=False,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='total_price::numeric(12, 2)',
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_sale_items_sale_id'), ['sale_id'], unique=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='total_amount::numeric(12, 2)',
               nullable=False,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('tax_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='tax_amount::numeric(12, 2)',
               nullable=False,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('discount_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='discount_amount::numeric(12, 2)',
               nullable=False,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('grand_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='grand_total::numeric(12, 2)',
               nullable=False,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'COMPLETED'::character varying"))
        batch_op.drop_index(batch_op.f('ix_sales_invoice_number'))
        batch_op.create_index(batch_op.f('ix_sales_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index('ix_sales_branch_created', ['branch_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index('ix_sales_branch_invoice', ['branch_id', 'invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_sales_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_sale_date'), ['sale_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_sale_date'))
        batch_op.drop_index(batch_op.f('ix_sales_created_at'))
        batch_op.drop_index('ix_sales_branch_invoice')
        batch_op.drop_index(batch_op.f('ix_sales_branch_id'))
        batch_op.drop_index('ix_sales_branch_created')
        batch_op.drop_index(batch_op.f('ix_sales_invoice_number'))
        batch_op.create_index(batch_op.f('ix_sales_invoice_number'), ['invoice_number'], unique=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'COMPLETED'::character varying"))
        batch_op.alter_column('grand_total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('discount_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('tax_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_items_sale_id'))
        batch_op.alter_column('total_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('discount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('unit_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_purchase_date'))
        batch_op.drop_index(batch_op.f('ix_purchases_created_at'))
        batch_op.drop_index(batch_op.f('ix_purchases_branch_id'))
        batch_op.drop_index('ix_purchases_branch_created')
        batch_op.alter_column('grand_total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('discount_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('tax_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))

    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_items_purchase_id'))
        batch_op.alter_column('selling_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('mrp',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('purchase_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('gst_percentage',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('selling_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('mrp',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('units_per_pack')

    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_branch_timestamp')
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_branch_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_batch_id'))
        batch_op.alter_column('quantity_change',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_batches_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_branch_id'))
        batch_op.drop_index('ix_batches_branch_product')
        batch_op.drop_index('ix_batches_branch_expiry')
        batch_op.alter_column('selling_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('mrp',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('purchase_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('quantity_available',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('is_placeholder_batch')
        batch_op.drop_column('is_placeholder_expiry')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_customer_branch_phone', type_='unique')
        batch_op.drop_index(batch_op.f('ix_customers_phone_normalized'))
        batch_op.drop_index(batch_op.f('ix_customers_branch_id'))
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=False)
        batch_op.drop_column('whatsapp_opt_in_at')
        batch_op.drop_column('whatsapp_opt_in')
        batch_op.drop_column('phone_normalized')
        batch_op.drop_column('phone_raw')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_sale_id'))
        batch_op.drop_index(batch_op.f('ix_payments_id'))
        batch_op.drop_index(batch_op.f('ix_payments_branch_id'))

    op.drop_table('payments')
    with op.batch_alter_table('invoice_sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_sequences_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_sequences_financial_year'))
        batch_op.drop_index(batch_op.f('ix_invoice_sequences_branch_id'))

    op.drop_table('invoice_sequences')
    # ### end Alembic commands ###
