"""add_data_integrity_issues_table

Revision ID: 3fb8c97a3b4d
Revises: a2043cb53b71
Create Date: 2026-08-31 11:38:03.804510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb8c97a3b4d'
down_revision: Union[str, Sequence[str], None] = 'a2043cb53b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_integrity_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('issue_type', sa.Enum('MISSING_REQUIRED_FIELD', 'INVALID_FORMAT', 'INVALID_VALUE', 'BUSINESS_RULE_WARNING', 'NORMALIZED_VALUE', name='issuetypeenum'), nullable=False),
    sa.Column('severity', sa.Enum('VALID', 'NORMALIZED', 'MISSING', 'WARNING', 'ERROR', name='severityenum'), nullable=False),
    sa.Column('placeholder_value', sa.String(), nullable=True),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_integrity_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_integrity_issues_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_integrity_issues_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_integrity_issues_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_integrity_issues_id'), ['id'], unique=False)

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_branches_id'), ['id'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_branch_id'))

    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_batches_branch_id'))
        batch_op.drop_column('branch')

    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_branch_id'))
        batch_op.drop_column('branch')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_branch_id'))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_branch_id'))
        batch_op.drop_index(batch_op.f('ux_sales_branch_invoice'))
        batch_op.create_index(batch_op.f('ix_sales_invoice_number'), ['invoice_number'], unique=True)

    with op.batch_alter_table('store_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ux_store_settings_branch_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_branch_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('store_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_store_settings_branch_id'), ['branch_id'], unique=True)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_invoice_number'))
        batch_op.create_index(batch_op.f('ux_sales_branch_invoice'), ['branch_id', 'invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_sales_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_inventory_transactions_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_inventory_batches_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_id'))
        batch_op.alter_column('address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('data_integrity_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_integrity_issues_id'))
        batch_op.drop_index(batch_op.f('ix_data_integrity_issues_entity_type'))
        batch_op.drop_index(batch_op.f('ix_data_integrity_issues_entity_id'))
        batch_op.drop_index(batch_op.f('ix_data_integrity_issues_branch_id'))

    op.drop_table('data_integrity_issues')
    # ### end Alembic commands ###
