"""add_branch_and_print_gstin

Revision ID: a2043cb53b71
Revises: 296e8d3ad158
Create Date: 2026-08-27 13:47:19.773257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2043cb53b71'
down_revision: Union[str, Sequence[str], None] = '296e8d3ad158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch', sa.String(), nullable=True))
        batch_op.alter_column('quantity_available',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch', sa.String(), nullable=True))
        batch_op.alter_column('quantity_change',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('store_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('print_gstin', sa.Boolean(), nullable=True))

    # Populate default values for existing rows
    op.execute("UPDATE store_settings SET print_gstin = true WHERE print_gstin IS NULL")
    op.execute("UPDATE inventory_batches SET branch = 'Branch 1' WHERE branch IS NULL")
    op.execute("UPDATE inventory_transactions SET branch = 'Branch 1' WHERE branch IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_settings', schema=None) as batch_op:
        batch_op.drop_column('print_gstin')

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.alter_column('quantity_change',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('branch')

    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.alter_column('quantity_available',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('branch')

    # ### end Alembic commands ###
