"""Add product and inventory fields for internal billing system

Revision ID: b3737b9be128
Revises: 2a4742a37dfc
Create Date: 2026-08-26 13:39:50.225436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3737b9be128'
down_revision: Union[str, Sequence[str], None] = '2a4742a37dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturing_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('quantity_available', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('purchase_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mrp', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('selling_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('quantity')

    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sku', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('hsn_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gst_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_barcode'))
        batch_op.drop_column('is_archived')
        batch_op.drop_column('gst_percentage')
        batch_op.drop_column('hsn_code')
        batch_op.drop_column('sku')
        batch_op.drop_column('barcode')

    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('reference_type')

    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('selling_price')
        batch_op.drop_column('mrp')
        batch_op.drop_column('purchase_price')
        batch_op.drop_column('quantity_available')
        batch_op.drop_column('manufacturing_date')

    # ### end Alembic commands ###
