"""add_returns_and_audit_logs_tables

Revision ID: f68c470419b1
Revises: 31b48f987466
Create Date: 2026-09-01 15:50:53.998807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68c470419b1'
down_revision: Union[str, Sequence[str], None] = '31b48f987466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action_timestamp', ['action', 'timestamp'], unique=False)
        batch_op.create_index('ix_audit_branch_timestamp', ['branch_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('return_number', sa.String(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('total_refund', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.create_index('ix_returns_branch_created', ['branch_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index('ix_returns_branch_number', ['branch_id', 'return_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_returns_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_return_date'), ['return_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_return_number'), ['return_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_sale_id'), ['sale_id'], unique=False)

    op.create_table('return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('sale_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('restock_inventory', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], ),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('return_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_items_return_id'), ['return_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_return_items_return_id'))
        batch_op.drop_index(batch_op.f('ix_return_items_id'))

    op.drop_table('return_items')
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_returns_sale_id'))
        batch_op.drop_index(batch_op.f('ix_returns_return_number'))
        batch_op.drop_index(batch_op.f('ix_returns_return_date'))
        batch_op.drop_index(batch_op.f('ix_returns_id'))
        batch_op.drop_index(batch_op.f('ix_returns_created_at'))
        batch_op.drop_index('ix_returns_branch_number')
        batch_op.drop_index(batch_op.f('ix_returns_branch_id'))
        batch_op.drop_index('ix_returns_branch_created')

    op.drop_table('returns')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_branch_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('ix_audit_branch_timestamp')
        batch_op.drop_index('ix_audit_action_timestamp')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
