from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime
from app.schemas.customer import Customer

class SaleItemBase(BaseModel):
    product_id: int
    batch_id: int
    quantity: float = Field(..., gt=0)
    unit_price: float = Field(..., ge=0)
    discount: float = Field(default=0.0, ge=0)
    total_price: float = Field(..., ge=0)

class SaleItemCreate(SaleItemBase):
    class Config:
        from_attributes = True

class SaleItem(SaleItemBase):
    id: int
    sale_id: int
    # We could include a small product schema here if needed

    class Config:
        from_attributes = True

class SaleBase(BaseModel):
    customer_id: Optional[int] = None
    invoice_number: Optional[str] = None # Generated by backend if not provided
    total_amount: float = Field(default=0.0, ge=0)
    tax_amount: float = Field(default=0.0, ge=0)
    discount_amount: float = Field(default=0.0, ge=0)
    grand_total: float = Field(default=0.0, ge=0)
    payment_method: str = "Cash"
    branch: Optional[str] = "C-Scheme"

class SaleCreate(SaleBase):
    items: List[SaleItemCreate]

class Sale(SaleBase):
    id: int
    status: str
    created_by: int
    created_at: datetime
    sale_date: datetime
    customer: Optional[Customer] = None
    items: List[SaleItem] = []

    class Config:
        from_attributes = True
